/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ["class"],
    content: [
        './pages/**/*.{js,jsx}',
        './components/**/*.{js,jsx}',
        './app/**/*.{js,jsx}',
        './src/**/*.{js,jsx}',
    ],
    prefix: "",
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            colors: {
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
                sidebar: {
                    DEFAULT: "hsl(var(--sidebar))",
                    foreground: "hsl(var(--sidebar-foreground))",
                    border: "hsl(var(--sidebar-border))",
                    accent: "hsl(var(--sidebar-accent))",
                    "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
                    ring: "hsl(var(--sidebar-ring))",
                },
                blue: {
                    50: "#f1f3f6",
                    100: "#e3e7ec",
                    200: "#c9d2dc",
                    300: "#b1bcc8",
                    400: "#8793a1",
                    500: "#667180",
                    600: "#2f343d",
                    700: "#262b32",
                    800: "#1f232a",
                    900: "#161a1f",
                },
                purple: {
                    50: "#f3f4f6",
                    100: "#e7e9ee",
                    200: "#d0d6df",
                    300: "#b6bfcc",
                    400: "#8a96a8",
                    500: "#6c788a",
                    600: "#5a6473",
                    700: "#4b5462",
                    800: "#3b424e",
                    900: "#2a313b",
                },
                amber: {
                    50: "#faf6f0",
                    100: "#f3e9d8",
                    200: "#e8d7b8",
                    300: "#d9bf90",
                    400: "#c4a16d",
                    500: "#b08955",
                    600: "#9a7444",
                    700: "#7f5f38",
                    800: "#664c2f",
                    900: "#4f3b26",
                },
                emerald: {
                    50: "#f0f7f3",
                    100: "#dceddf",
                    200: "#c0dec9",
                    300: "#9bc9ad",
                    400: "#6db58a",
                    500: "#59b386",
                    600: "#4a9a73",
                    700: "#3e7f60",
                    800: "#346852",
                    900: "#2a5443",
                },
                slate: {
                    50: "#f6f7f9",
                    100: "#eceff3",
                    200: "#d9dee6",
                    300: "#c4cad6",
                    400: "#9ba4b4",
                    500: "#7a8491",
                    600: "#5f6773",
                    700: "#4a515c",
                    800: "#373d47",
                    900: "#2f343d",
                },
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
                xl: "18px",
                "2xl": "22px",
            },
            boxShadow: {
                soft: "0 8px 24px rgba(23, 28, 38, 0.08)",
                "soft-lg": "0 20px 40px rgba(23, 28, 38, 0.12)",
                "soft-inset": "inset 0 1px 0 rgba(255, 255, 255, 0.6)",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
            fontFamily: {
                sans: ["Poppins", "sans-serif"],
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
}
